name: Pull Request Automation

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest build

      - name: Lint with pylint
        run: |
          pylint fastapi_pr_demo/*.py tests/*.py --fail-under=7.0

      - name: Run tests with pytest
        run: |
          pytest

      - name: Build Python package
        run: |
          python -m build

      - name: Upload package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: fastapi-package
          path: dist/*
